name: test1
on:
  push:
    branches:
      - main
  jobs:
    subtest1:
      runs-on: ubuntu-lastest
      steps:
      name: step1
      run: echo "hello world"
      name: step2
      run: echo "how do you do"
