name: test3
on:
  push:
    branches:
      - main
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello world"
      - name: step2
        run: echo "Buy world"
      
