name: test3
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "this is job1 step1"
      - name: step2
        run: echo "this is job1 step2"
  job2:
    runs-on: centos-latest
    steps:
      - name: step1
        run: echo "this is job2 step1"
      - name: step2
        run: echo "this is job2 step2"
