name: test3
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello world"
      - name: step2
        run: echo "Buy world"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name step1
        run: echo "hello2 wolrd"
      - name step2
        run: echo "buy2 world"
